install.packages("highr")
install.packages("markdown")
install.packages("stringr")
install.packages("yaml")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("https://cran.r-project.org/src/contrib/Archive/tidyselect/tidyselect_1.1.0.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_1.0.6.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/V8/V8_4.1.0.tar.gz", repos = NULL, type = "source")
#install.packages('rstan')
devtools::install_version("rstan","2.21.5", repos = "https://cran.r-project.org/")
