install.packages("highr")
install.packages("markdown")
install.packages("stringr")
install.packages("yaml")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("https://cran.r-project.org/src/contrib/Archive/tidyselect/tidyselect_1.1.0.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_1.0.6.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/V8/V8_4.1.0.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/Rcpp/Rcpp_1.0.7.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/RcppEigen/RcppEigen_0.3.3.9.1.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/BH/BH_1.75.0-0.tar.gz", repos = NULL, type = "source")
install.packages("https://cran.r-project.org/src/contrib/Archive/RcppParallel/RcppParallel_5.1.4.tar.gz", repos = NULL, type = "source")
install.packages("StanHeaders", version = "2.26.13", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
install.packages("rstan", dependencies = TRUE)
